"""
Módulo generado automáticamente desde Qt Designer usando pyuic6.

Define la clase `Ui_CalculadoraAreas`, que configura la interfaz principal de la aplicación.
Esta clase no contiene lógica de negocio, solo elementos visuales.
"""
# Form implementation generated from reading ui file 'calculo_de_areas/src/vista/ventana_areas.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CalculadoraAreas(object):
    """
    Clase generada automáticamente que representa la interfaz gráfica de la calculadora de áreas.
    """

    def setupUi(self, CalculadoraAreas):
        """
        Configura todos los elementos visuales de la ventana principal.

        :param CalculadoraAreas: Instancia de QMainWindow donde se colocarán los elementos.
        """
        CalculadoraAreas.setObjectName("CalculadoraAreas")
        CalculadoraAreas.resize(344, 349)

        self.centralwidget = QtWidgets.QWidget(parent=CalculadoraAreas)
        self.centralwidget.setObjectName("centralwidget")
        CalculadoraAreas.setCentralWidget(self.centralwidget)

        self.menubar = QtWidgets.QMenuBar(parent=CalculadoraAreas)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 344, 21))
        self.menubar.setObjectName("menubar")

        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")

        self.menuCalculo_de_areas = QtWidgets.QMenu(parent=self.menubar)
        self.menuCalculo_de_areas.setObjectName("menuCalculo_de_areas")

        CalculadoraAreas.setMenuBar(self.menubar)

        self.statusbar = QtWidgets.QStatusBar(parent=CalculadoraAreas)
        self.statusbar.setObjectName("statusbar")
        CalculadoraAreas.setStatusBar(self.statusbar)

        # Acciones del menú
        self.actionSalir = QtGui.QAction(parent=CalculadoraAreas)
        self.actionSalir.setObjectName("actionSalir")

        self.actionArea_del_circulo = QtGui.QAction(parent=CalculadoraAreas)
        self.actionArea_del_circulo.setObjectName("actionArea_del_circulo")

        self.actionArea_del_triangulo = QtGui.QAction(parent=CalculadoraAreas)
        self.actionArea_del_triangulo.setObjectName("actionArea_del_triangulo")

        self.actionArea_del_rectangulo = QtGui.QAction(parent=CalculadoraAreas)
        self.actionArea_del_rectangulo.setObjectName("actionArea_del_rectangulo")

        self.actionArea_del_cuadrado = QtGui.QAction(parent=CalculadoraAreas)
        self.actionArea_del_cuadrado.setObjectName("actionArea_del_cuadrado")

        self.actionMenu = QtGui.QAction(parent=CalculadoraAreas)
        self.actionMenu.setObjectName("actionMenu")

        # Agregando acciones a los menús
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSalir)

        self.menuCalculo_de_areas.addAction(self.actionArea_del_circulo)
        self.menuCalculo_de_areas.addAction(self.actionArea_del_triangulo)
        self.menuCalculo_de_areas.addAction(self.actionArea_del_rectangulo)
        self.menuCalculo_de_areas.addAction(self.actionArea_del_cuadrado)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuCalculo_de_areas.menuAction())

        # Traducción de textos
        self.retranslateUi(CalculadoraAreas)

        # Conexión automática de señales y slots
        QtCore.QMetaObject.connectSlotsByName(CalculadoraAreas)

    def retranslateUi(self, CalculadoraAreas):
        """
        Traduce los textos de los widgets para la interfaz en distintos idiomas.

        :param CalculadoraAreas: Ventana principal para aplicar los textos.
        """
        _translate = QtCore.QCoreApplication.translate
        CalculadoraAreas.setWindowTitle(_translate("CalculadoraAreas", "MainWindow"))
        self.menuFile.setTitle(_translate("CalculadoraAreas", "File"))
        self.menuCalculo_de_areas.setTitle(_translate("CalculadoraAreas", "Calculo de areas"))
        self.actionSalir.setText(_translate("CalculadoraAreas", "Salir"))
        self.actionArea_del_circulo.setText(_translate("CalculadoraAreas", "Circulo"))
        self.actionArea_del_triangulo.setText(_translate("CalculadoraAreas", "Triangulo"))
        self.actionArea_del_rectangulo.setText(_translate("CalculadoraAreas", "Rectangulo"))
        self.actionArea_del_cuadrado.setText(_translate("CalculadoraAreas", "Cuadrado"))
        self.actionMenu.setText(_translate("CalculadoraAreas", "Menu"))
